### ISSUE TITLE
"Setup" Page not configured correctly

### ISSUE THREAD

**Issue by arieldeardorff** [LibraryCarpentry/lc-r#11]
The ["Setup" page](http://librarycarpentry.org/lc-r/setup.html) listed on the [main lesson menu](http://librarycarpentry.org/lc-r/index.html) still has placeholder text. I think this page should have instructions for downloading R and RStudio, correct?

**Comment by stragu** [comment]
Any reason why this hasn't been merged? It would make perfect sense. Then we can finetune it.

**Comment by libjohn** [comment]
I think the main reason is that most of the active lesson contributors are all carpentry newbies with respect to creating carpentry lessons.  We haven't had a chance to discuss how to merge in all the requests.  Hopefully we'll have another meeting soon.  That said....  

This looks pretty straight forward.  It's been in the queue a while, and now it's getting bumped for action.  I'm going to merge the request.  Thanks @annajiat and @arieldeardorff for the ideas.   Thanks @stragu for the bump.  

I'm a newbie too so if my merge is a procedural error, I only ask for some gentle explanation from carpentry veterans.

**peace, love, and understanding**
-- John
