### ISSUE TITLE
Data viz: reformat code lines 125-126

### ISSUE THREAD

**Issue by libjohn** [LibraryCarpentry/lc-r#19]
[data viz lesson](https://github.com/LibraryCarpentry/lc-r/blob/gh-pages/_episodes_rmd/04-data-viz-ggplot.Rmd) | [code @ lines 125-126](https://github.com/LibraryCarpentry/lc-r/blob/7d79490df929407480b122fb761fff9c30a4f7ff/_episodes_rmd/04-data-viz-ggplot.Rmd#L125)

### Original

```
booksPlot <- books2 %>%
  filter(subCollection == "general collection" |  subCollection == "juvenile" |  subCollection == "k-12 materials",
         !is.na(call_class))
```

### Proposed

```
booksPlot <- books2 %>%
  filter(subCollection == "general collection" | 
           subCollection == "juvenile" | 
           subCollection == "k-12 materials",
         !is.na(call_class))
```

**Comment by libjohn** [comment]
merged https://github.com/LibraryCarpentry/lc-r/pull/31

**Comment by stragu** [comment]
I know this issue is already closed, but I think is would be better to use `%in%` here, like so:

```r
booksPlot <- books2 %>%
  filter(subCollection %in% c("general collection", "juvenile", "k-12 materials"),
         !is.na(call_class))
```

Unless we have a strong reason to introduce the OR operator here?
OR is very useful, but as soon as there are a couple of comparisons to the same variable, I consider %in% to be a lot neater.
