### ISSUE TITLE
Draft lessons

### ISSUE THREAD

**Issue by ciakovx** [LibraryCarpentry/lc-r#2]
Hello everyone,

I dropped in a draft set of lessons on Intro to R using some library circulation data. It is adapted from a previous lesson I created, available at https://ciakovx.github.io/fsci_syllabus.html.

I thought this would be an easier way for us to review it together and check its feasibility going forward. **I am fully open to any feedback you have**, including starting something new. I am happy to discuss any issues or suggestions, as well as some of the alternatives that were raised on the other [open issue](https://github.com/LibraryCarpentry/lc-r/issues/1).

I know things are uncertain with everything going on right now, but are you all available for a conversation sometime during the next couple of weeks to develop a plan for this? If so, respond below and I will set up a Doodle poll

**Comment by jt14den** [comment]
@ciakovx great work with this. How can I help out?
