### ISSUE TITLE
Intro to R: Typos under "Evaluating Expressions"

### ISSUE THREAD

**Issue by arieldeardorff** [LibraryCarpentry/lc-r#22]
Under "Evaluating Expressions" on the [Intro to R ](http://librarycarpentry.org/lc-r/01-intro-to-r/index.html) episode it mentions printing "Y" and getting 5 in return. Unless I missed it I don't think we ever assigned 5 to Y (we did assign it to "time_minutes"). The first code box under "Evaluating Expressions" also refers to the "value of Y" in the comment.

**Comment by ciakovx** [comment]
This has been fixed #27
