### ISSUE TITLE
move pattern matching down the data cleaning & transformation episode

### ISSUE THREAD

**Issue by jt14den** [LibraryCarpentry/lc-r#64]
On: https://librarycarpentry.org/lc-r/03-data-cleaning-and-transformation/index.html

Introducing regexes might be taxing on the learner. I suggest moving it below Putting it all together & Split Apply Combine.  It could also work as an aside or a challenge that introduces new concepts.

**Comment by SangareB** [comment]
I agree with the suggestion to 
 
Insert **Regex is especially useful for manipulating strings (alphanumeric data) and is the backbone of search-and-replace operations in most applications under Split-apply-combine data analysis and the `summarize()` function, in conclusion, this will serve as another way to run the command for those who are familiar with Regex
