### ISSUE TITLE
Replace spread and gather with the newer functions from tidyr

### ISSUE THREAD

**Issue by chrbknudsen** [LibraryCarpentry/lc-r#79]
In "Date cleaning & transformation with dplyr", objectives lists "spread" and "gather". 
They are not mentioned in the lesson. But if they are, they should be replaced with pivot_wider and pivot_longer, as spread and gather are superseded.

**Comment by rsangole** [comment]
I'm happy to work on this issue as my first contribution, if it's still valuable to resolve (given it's over a year old!)

**Comment by chrbknudsen** [comment]
As I understand it the lessons are being migrated which might influence the value of resolving. But spread and gather are even more out of date a year later :) pivot_wider/pivot_longer is the way to go instead.

**Comment by tobyhodges** [comment]
> As I understand it the lessons are being migrated which might influence the value of resolving.

Indeed as @chrbknudsen says, [the lesson will switch over to the new infrastructure next week](https://github.com/LibraryCarpentry/lc-r/issues/88), so I would not recommend starting to make any changes before that has happened. The same is true for any other lessons that have not already completed the infrastructure transition - this page provides an overview of the current state of each of The Carpentries lessons: https://carpentries.github.io/workbench/transition-schedule.html

**Comment by rsangole** [comment]
Gotcha, makes sense. Then I'll simply wait for the migration to finish before picking out the next set of issues to resolve.

**Comment by jt14den** [comment]
This looks resolved in the episode.
