### ISSUE TITLE
Move to alpha

### ISSUE THREAD

**Issue by jt14den** [LibraryCarpentry/lc-r#8]
A suggestion we move this lesson to alpha and teach it.

**Comment by arieldeardorff** [comment]
Definitely agree! This lesson is way beyond conceptual at this point.

**Comment by jt14den** [comment]
@arieldeardorff At the maintainer meeting we agreed to move it forward and I volunteered to submit a PR, but if you beat me to it I'll merge :)

**Comment by arieldeardorff** [comment]
Where do you officially change the status? On the [LC lessons page](https://librarycarpentry.org/lessons/)? Or somewhere in the lesson? Or both?

**Comment by jt14den** [comment]
It's set in `_config.yml`, you can see in lc spreadsheet: https://github.com/LibraryCarpentry/lc-spreadsheets/blob/gh-pages/_config.yml

**Comment by arieldeardorff** [comment]
Pull request submitted! Should we also update the table on the [LC lessons page](https://librarycarpentry.org/lessons/)? Currently it is buried down in the "conceptual" section but not sure how all of that is decided...

**Comment by jt14den** [comment]
@arieldeardorff, yeah we should change that too.
