### ISSUE TITLE
Broken links on "Contributing" page

### ISSUE THREAD

**Issue by smsura** [LibraryCarpentry/lc-r#83]
On the "Contributing" page under the "Where to contribute" , both links in 1 are broken. Under "Using GitHub" the link for [How to Contribute to an Open Source Project on GitHub] is also broken and should be updated to https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github

**Comment by claudiakapp** [comment]
I ran into the same issue. It appears that `https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github
` is the correct link.
It appears that they changed the URL from https://egghead.io/**series**/... to https://egghead.io/**courses**/...

**Comment by jt14den** [comment]
fixed with #92
